config/routes.rb
CodefellowsTest::Application.routes.draw do
  resources :user_question_sets

  resources :user_enrollments

  resources :questions do
    resources :answers
  end

  resources :offerings

  devise_for :users
  get '/user_enrollments' => 'user_enrollments#delete_user', as: 'delete_user'

  devise_scope :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

   root 'offerings#index'

end

app/models/offering.rb
class Offering < ActiveRecord::Base
	belongs_to :user_enrollment

end

app/controllers/offerings_controller.rb
class OfferingsController < ApplicationController
  before_action :set_offering, only: [:show, :edit, :update, :destroy]

  # GET /offerings
  # GET /offerings.json
  def index
    @offerings = Offering.all
  end

  # GET /offerings/1
  # GET /offerings/1.json
  def show

  end

  # GET /offerings/new
  def new
    @offering = Offering.new
  end

  # GET /offerings/1/edit
  def edit
  end

  # POST /offerings
  # POST /offerings.json
  def create
    @offering = Offering.new(offering_params)

    respond_to do |format|
      if @offering.save
        format.html { redirect_to @offering, notice: 'Offering was successfully created.' }
        format.json { render action: 'show', status: :created, location: @offering }
      else
        format.html { render action: 'new' }
        format.json { render json: @offering.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offerings/1
  # PATCH/PUT /offerings/1.json
  def update
    respond_to do |format|
      if @offering.update(offering_params)
        format.html { redirect_to @offering, notice: 'Offering was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @offering.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offerings/1
  # DELETE /offerings/1.json
  def destroy
    @offering.destroy
    respond_to do |format|
      format.html { redirect_to offerings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offering
      @offering = Offering.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offering_params
      params.require(:offering).permit(:name, :offering_type_id, :city_id, :description, :location_id,
                                       :starts_at, :ends_at, :max_enrollment, :created_at, :updated_at,
                                       :deadline_at, :tuition_cost, :deposit_cost, :code, :user_enrollment_id)
    end
end

app/helpers/offerings_helper.rb
module OfferingsHelper
end

app/views/offerings/_form.html.erb
<%= form_for(@offering) do |f| %>
  <% if @offering.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offering.errors.count, "error") %> prohibited this offering from being saved:</h2>

      <ul>
      <% @offering.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :detail %><br>
    <%= f.text_area :detail %>
  </div>
  <div  class="field">
    <%= f.label :start_date %><br>
    <%= f.date_field :start_date %>

  </div>
    <div  class="field">
    <%= f.label :end_date %><br>
    <%= f.date_field :end_date %>

  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offerings/edit.html.erb
<h1>Editing offering</h1>

<%= render 'form' %>

<%= link_to 'Show', @offering %> |
<%= link_to 'Back', offerings_path %>

app/views/offerings/index.html.erb
<h1>Listing offerings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @offerings.each do |offering| %>
      <tr>
        <td><%= offering.name %></td>
        <td><%= offering.starts_at %></td>
        <td><%= offering.ends_at %></td>

        <td><%= link_to 'Show', offering %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Offering', new_offering_path %>


<% if current_user %>
  <% if current_user.user_enrollment%>
    <%= link_to "View application",user_enrollment_path(current_user.user_enrollment)%>
  <%else %>
    <%= link_to "Apply now",new_user_enrollment_path%>
  <% end %>
<% end %>

app/views/offerings/new.html.erb
<h1>New offering</h1>

<%= render 'form' %>

<%= link_to 'Back', offerings_path %>

app/views/offerings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @offering.name %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @offering.detail %>
</p>

<p>
  <strong>Start Date:</strong>
  <%= @offering.start_date %>
</p>


<p>
  <strong>End Date:</strong>
  <%= @offering.end_date %>
</p>

<%= link_to 'Edit', edit_offering_path(@offering) %> |
<%= link_to 'Back', offerings_path %>