config/routes.rb
CodefellowsTest::Application.routes.draw do
  resources :user_question_sets

  resources :user_enrollments

  resources :questions do
    resources :answers
  end

  resources :offerings

  devise_for :users
  get '/user_enrollments' => 'user_enrollments#delete_user', as: 'delete_user'

  devise_scope :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

   root 'offerings#index'

end

app/models/user_question_set.rb
class UserQuestionSet < ActiveRecord::Base
  belongs_to :user
  belongs_to :user_enrollment
  has_many :questions

end

app/controllers/user_question_sets_controller.rb
class UserQuestionSetsController < ApplicationController
  before_action :set_user_question_set, only: [:show, :edit, :update, :destroy]

  # GET /user_question_sets
  # GET /user_question_sets.json
  def index
    @user_question_sets = UserQuestionSet.all
  end

  # GET /user_question_sets/1
  # GET /user_question_sets/1.json
  def show
  end

  # GET /user_question_sets/new
  def new
    @user_question_set = UserQuestionSet.new
  end

  # GET /user_question_sets/1/edit
  def edit
  end

  # POST /user_question_sets
  # POST /user_question_sets.json
  def create
    @user_question_set = UserQuestionSet.new(user_question_set_params)

    respond_to do |format|
      if @user_question_set.save
        format.html { redirect_to @user_question_set, notice: 'User question set was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_question_set }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_question_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_question_sets/1
  # PATCH/PUT /user_question_sets/1.json
  def update
    respond_to do |format|
      if @user_question_set.update(user_question_set_params)
        format.html { redirect_to @user_question_set, notice: 'User question set was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_question_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_question_sets/1
  # DELETE /user_question_sets/1.json
  def destroy
    @user_question_set.destroy
    respond_to do |format|
      format.html { redirect_to user_question_sets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_question_set
      @user_question_set = UserQuestionSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_question_set_params
      params.require(:user_question_set).permit(:user_id, :question_set_id, :created_at, :updated_at, :user_enrollment_id)
    end
end

app/helpers/user_question_sets_helper.rb
module UserQuestionSetsHelper
end

app/views/user_question_sets/_form.html.erb
<%= form_for(@user_question_set) do |f| %>
  <% if @user_question_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_question_set.errors.count, "error") %> prohibited this user_question_set from being saved:</h2>

      <ul>
      <% @user_question_set.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :question_set_id %><br>
    <%= f.text_field :question_set_id %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.text_field :created_at %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br>
    <%= f.text_field :updated_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_question_sets/edit.html.erb
<h1>Editing user_question_set</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_question_set %> |
<%= link_to 'Back', user_question_sets_path %>

app/views/user_question_sets/index.html.erb
<h1>Listing user_question_sets</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Question set</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_question_sets.each do |user_question_set| %>
      <tr>
        <td><%= user_question_set.user_id %></td>
        <td><%= user_question_set.question_set_id %></td>
        <td><%= user_question_set.created_at %></td>
        <td><%= user_question_set.updated_at %></td>
        <td><%= link_to 'Show', user_question_set %></td>
        <td><%= link_to 'Edit', edit_user_question_set_path(user_question_set) %></td>
        <td><%= link_to 'Destroy', user_question_set, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User question set', new_user_question_set_path %>

app/views/user_question_sets/new.html.erb
<h1>New user_question_set</h1>

<%= render 'form' %>

<%= link_to 'Back', user_question_sets_path %>

app/views/user_question_sets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_question_set.user_id %>
</p>

<p>
  <strong>Question set:</strong>
  <%= @user_question_set.question_set_id %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @user_question_set.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @user_question_set.updated_at %>
</p>

<%= link_to 'Edit', edit_user_question_set_path(@user_question_set) %> |
<%= link_to 'Back', user_question_sets_path %>