config/routes.rb
CodefellowsTest::Application.routes.draw do
  resources :user_question_sets

  resources :user_enrollments

  resources :questions do
    resources :answers
  end

  resources :offerings

  devise_for :users
  get '/user_enrollments' => 'user_enrollments#delete_user', as: 'delete_user'

  devise_scope :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

   root 'offerings#index'

end

app/models/user_enrollment.rb
class UserEnrollment < ActiveRecord::Base
  belongs_to :user
  has_many :offerings
  has_many :user_question_sets
end

app/controllers/user_enrollments_controller.rb
class UserEnrollmentsController < ApplicationController
  before_filter :check_logged_in_user, except: [:index, :delete_user]
  before_action :set_user_enrollment, only: [:show, :edit, :update, :destroy]

  # GET /user_enrollments
  # GET /user_enrollments.json
  def index
    @user_enrollments = UserEnrollment.all
  end

  # GET /user_enrollments/1
  # GET /user_enrollments/1.json
  def show
    if @user_enrollments.user_id != current_user.id
      redirect_to root_path
    end
  end

  # GET /user_enrollments/new
  def new
    if current_user.user_enrollment
      redirect_to root_path
    else
      @user_enrollment = UserEnrollment.new
    end
  end

  # GET /user_enrollments/1/edit
  def edit
  end

  # POST /user_enrollments
  # POST /user_enrollments.json
  def create
    @user_enrollment = UserEnrollment.new(user_enrollment_params)
    @user_enrollments.user_id != current_user.id
    respond_to do |format|
      if @user_enrollment.save
        format.html { redirect_to @user_enrollment, notice: 'User enrollment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_enrollment }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_enrollments/1
  # PATCH/PUT /user_enrollments/1.json
  def update
    respond_to do |format|
      if @user_enrollment.update(user_enrollment_params)
        format.html { redirect_to @user_enrollment, notice: 'User enrollment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_enrollments/1
  # DELETE /user_enrollments/1.json
  def destroy
    @user_enrollment.destroy
    respond_to do |format|
      format.html { redirect_to user_enrollments_url }
      format.json { head :no_content }
    end
  end

  def delete_user
    user_id = params[:format]
    User.find(user_id).destroy
    redirect_to user_sessions_path
  end

    private


    def check_logged_in_user
      if !current_user
        redirect_to root_path
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user_enrollment
      if current_user
        @user_enrollment = current_user.user_enrollment
      else
        @user_enrollment = UserEnrollment.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_enrollment_params
      params.require(:user_enrollment).permit(:user_id, :offering_id, :status, :created_at,
       :updated_at)
    end
  end

app/helpers/user_enrollments_helper.rb
module UserEnrollmentsHelper
end

app/views/user_enrollments/_form.html.erb
<%= form_for(@user_enrollment) do |f| %>
  <% if @user_enrollment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_enrollment.errors.count, "error") %> prohibited this user_enrollment from being saved:</h2>

      <ul>
      <% @user_enrollment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :offering_id %><br>
    <%= f.text_field :offering_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.text_field :created_at %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br>
    <%= f.text_field :updated_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_enrollments/edit.html.erb
<h1>Editing user_enrollment</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_enrollment %> |
<%= link_to 'Back', user_enrollments_path %>

app/views/user_enrollments/index.html.erb
<h1>Listing user_enrollments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Offering</th>
      <th>Status</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_enrollments.each do |user_enrollment| %>
      <tr>
        <td><%= user_enrollment.user_id %></td>
        <td><%= user_enrollment.offering_id %></td>
        <td><%= user_enrollment.status %></td>
        <td><%= user_enrollment.created_at %></td>
        <td><%= user_enrollment.updated_at %></td>
        <td><%= link_to 'Show', user_enrollment %></td>
        <td><%= link_to 'Edit', edit_user_enrollment_path(user_enrollment) %></td>
        <td><%= link_to 'Destroy', user_enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User enrollment', new_user_enrollment_path %>

app/views/user_enrollments/new.html.erb
<h1>New user_enrollment</h1>

<%= render 'form' %>

<%= link_to 'Back', user_enrollments_path %>

app/views/user_enrollments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_enrollment.user_id %>
</p>

<p>
  <strong>Offering:</strong>
  <%= @user_enrollment.offering_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @user_enrollment.status %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @user_enrollment.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @user_enrollment.updated_at %>
</p>

<%= link_to 'Edit', edit_user_enrollment_path(@user_enrollment) %> |
<%= link_to 'Back', user_enrollments_path %>